id: os_sudo_timeout_configure
title: "Configure Sudo Timeout Period to $ODV"
discussion: |
  The file /etc/sudoers _MUST_ include a timestamp_timout of $ODV.
check: |
  /usr/bin/find /etc/sudoers* -type f -exec /usr/bin/grep -E "^Defaults\s+timestamp_timeout=$ODV" '{}' \; | /usr/bin/wc -l | /usr/bin/xargs
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/find /etc/sudoers* -type f -exec sed -i '' '/timestamp_timeout/d' '{}' \;
  /bin/echo "Defaults timestamp_timeout=$ODV" >> /etc/sudoers.d/mscp
  ----
references:
  cce:
    - N/A
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  cis:
    benchmark:
      - 5.3 (level 1)
    v8:
      - 4.3
macOS:
  - "12.0"
odv:
  hint: "number of minutes"
  default: 0
  cis_lvl1: 0
  cis_lvl2: 0
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - test
mobileconfig: false
mobileconfig_info: