id: system_settings_siri_prefpane_disable
title: "Disable the System Preference Pane for Siri"
discussion: |
  The system preference pane for Siri _MUST_ be disabled.

  Disabling the system preference pane prevents the users from configuring Siri. This will also hide the Siri System Setting.
check: |
  /usr/bin/profiles -P -o stdout | /usr/bin/grep -c 'com.apple.preference.speech' | /usr/bin/awk '{ if ($1 >= 2) {print "1"} else {print "0"}}' 
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91977-9
  cci: 
    - CCI-001774
    - CCI-000381
  800-53r5:
    - CM-7
    - CM-7(5)
  800-53r4: 
    - CM-7
    - CM-7(5)
  srg: 
    - SRG-OS-000095-GPOS-00049
  disa_stig: 
    - APPL-12-002053
  800-171r2:
    - N/A
macOS:
  - "13.0"
tags:
  - stig
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.systempreferences:
    DisabledPreferencePanes: 
      - com.apple.preference.speech
